version: '3.8'

services:
  bot:
    build: .
    restart: always
    environment:
      # Тут підставляться твої змінні з файлу .env
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - USE_POLLING=true
      # Налаштування бази даних (автоматично лінкується з сервісом db нижче)
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
      - DB_NAME=spygame
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: spygame
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: